import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href="/">
             <div>
              Home 
              <Image src="/favicon.jpg" alt="Vercel Logo" width={72} height={16} />

             </div>
          </Link>

          <br />


        </div>
        {children}
        
        </body>
    </html>
  );
}
